* AUTO-REGISTERING A GENERIC MODEL TO ENTERPRISE DECISION MANAGER; 
								
* SET THE FOLLOWING PARAMETERS;
%let MM_Folder 	= Marketing/New_Product_Propensity;
%let Version_ID 	= 1.0;
%let Model_Name 	= New_Model_Ensemble;

* Load and access the Model Management macro code;
filename MMAccess catalog 'SASHELP.modelmgr.AccessMacros.source';
%include MMAccess;
 
* Set RC flag to detect failure in case macro load fails;
%let _MM_RC= -1;
 
* Automatically extract the file for the score code generated by the Score Node connected to this SAS Code Node;
data _null_;
	DIAGRAM_PATH = substr("&EM_NODEDIR.", 1, length("&EM_NODEDIR.")-length(scan("&EM_NODEDIR.", -1, "\"))-1);
	Code = trim(left(DIAGRAM_PATH)) || "\" || "&EM_METASOURCE_NODEID." || "\" || "PATHPUBLISHSCORECODE.sas";
	call symput ("Score_File", trim(left(Code)));
run;
filename Code "&Score_File.";

* Export the input variable names before transformations into a macro variable called SCORE_INPUT_VARS;
proc sql;
  select NAME into :SCORE_INPUT_VARS separated by ' '  from &EM_LIB..&EM_METASOURCE_NODEID._EMINPUTVARS where role="INPUT";
  select NAME into :SCORE_TARGET_VAR separated by ' '  from &EM_LIB..&EM_METASOURCE_NODEID._EMINPUTVARS where role="TARGET";
quit;

* Prepare datasets for Model Manager- the input, output and target tables that will be used for xml definitions;
data INPUT_DS;		set &EM_LIB..&EM_METASOURCE_NODEID._TRAIN (keep= &SCORE_INPUT_VARS. obs=1);		run;
data OUTPUT_DS;	format EM_EVENTPROBABILITY 8.3;		run;
data TARGET_DS;	format &SCORE_TARGET_VAR. 8.;	run;
 
* Register the model in the model repository;
%MM_Register(
	VersionId				= //ModelManagerDefaultRepo/MMRoot/&MM_Folder./&Version_ID.,
 	ScoreDataStepCode		= Code,
 	InDataSamp				= INPUT_DS,
 	OutDataSamp				= OUTPUT_DS,
 	TargetDataSamp			= TARGET_DS,
	ModelName				= &Model_Name.,
 	Description				= &Score_File.,
 	Trace						= ON);
 
* Display the RC flag after run;
%PUT _MM_RC = &_MM_RC;
/* End of file. */
 
 
 
 
 
 
